version: '3.8'

services:
  # SonarQube 服务器
  sonarqube:
    image: sonarqube:10.3-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar123
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    depends_on:
      - sonar-postgres
    networks:
      - sonar-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # PostgreSQL 数据库用于 SonarQube
  sonar-postgres:
    image: postgres:15-alpine
    container_name: sonar-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar123
      - POSTGRES_DB=sonar
    volumes:
      - sonar-postgres-data:/var/lib/postgresql/data
    networks:
      - sonar-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  sonar-postgres-data:

networks:
  sonar-network:
    driver: bridge 