server:
  port: 8081
  
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:13306/chat_user_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

chatapp:
  app:
    jwtSecret: myVeryVerySecretKeyThatNeedsToBeAtLeast32CharactersLongForHS512Algorithm
    jwtExpirationMs: 86400000 # 24小时

logging:
  level:
    com.chatapp.user: DEBUG
    org.springframework.security: INFO 